AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/**/*'
   - 'config/application.rb'
   - 'config/environments/*'
   - 'test/test_helper.rb'

Style/AsciiComments:
  Enabled: false
