AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/**/*'
   - 'config/application.rb'
   - 'config/environments/*'
   - 'test/support/**/*'

Rails:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: true
  Exclude:
    - 'test/test_helper.rb'

Style/Documentation:
  Enabled: true
  Exclude:
    - 'test/**/*'
    - 'db/migrate/*'
